SECRET_DIST = "secret dist."
LAMBDA = "lambda"
LOG_Q = "log q"
USVP = "usvp"
LWE_USVP = "est usvp"
USVP_S = "usvp_s"
LWE_USVP_S = "est usvp_s"
USVP_NUM = "usvp num"
LWE_NUM = "est num"
BDD = "bdd"
LWE_BDD = "est bdd"
BDD_S = "bdd_s"
LWE_BDD_S = "est bdd_s"
BDD_NUM = "bdd num"
OUTPUT = "output"
POW = "pow"
LWE_DIM = "lwe dim."
LOGQ_USVP = "logq usvp"
LOGQ_BDD = "logq bdd"
HW = "hw"
HYBRID = "hybrid"
LWE_HYBRID = "est hybrid"
STD_E_USVP = "log2(std_e) usvp"
STD_E_BDD = "log2(std_e) bdd"
NUM_USVP = "num usvp"
NUM_BDD = "num bdd"
LWE = "est"

HEADERS_N_VERIFY = [SECRET_DIST, LAMBDA, LOG_Q, USVP, LWE_USVP, USVP_S, LWE_USVP_S, USVP_NUM, LWE_NUM, BDD, LWE_BDD, BDD_S, LWE_BDD_S, BDD_NUM, LWE_NUM, OUTPUT, POW]
HEADERS_N_NO_VERIFY = [SECRET_DIST, LAMBDA, LOG_Q, USVP, USVP_S, USVP_NUM, BDD, BDD_S, BDD_NUM, OUTPUT, POW]
HEADERS_LOGQ_VERIFY = [SECRET_DIST, LAMBDA, LWE_DIM, LOGQ_USVP, LOGQ_BDD, LWE_USVP, LWE_BDD]
HEADERS_LOGQ_NO_VERIFY = [SECRET_DIST, LAMBDA, LWE_DIM, LOGQ_USVP, LOGQ_BDD]
HEADERS_LOGQ_HYBRID_VERIFY = [SECRET_DIST, LWE_DIM, LAMBDA, HW, HYBRID, LWE_HYBRID]
HEADERS_LOGQ_HYBRID_NO_VERIFY = [SECRET_DIST, LWE_DIM, LAMBDA, HW, HYBRID]
HEADERS_STD_E_VERIFY = [SECRET_DIST, LAMBDA, LWE_DIM, LOG_Q, STD_E_USVP, STD_E_BDD, LWE_USVP, LWE_BDD, OUTPUT]
HEADERS_STD_E_NO_VERIFY = [SECRET_DIST, LAMBDA, LWE_DIM, LOG_Q, NUM_USVP, NUM_BDD, OUTPUT]
HEADERS_LAMBDA_VERIFY = [SECRET_DIST, LWE_DIM, LOG_Q, USVP, LWE_USVP, USVP_S, BDD, LWE_BDD, BDD_S, OUTPUT]
HEADERS_LAMBDA_NO_VERIFY = [SECRET_DIST, LWE_DIM, LOG_Q, USVP, USVP_S, BDD, BDD_S, OUTPUT]
HEADERS_LAMBDA_ALT_VERIFY = [SECRET_DIST, LWE_DIM, LOG_Q, USVP, LWE_USVP, BDD, LWE_BDD, OUTPUT]
HEADERS_LAMBDA_ALT_NO_VERIFY = [SECRET_DIST, LWE_DIM, LOG_Q, USVP, BDD, OUTPUT]
HEADERS_LAMBDA_HYBRID_VERIFY = [SECRET_DIST, LWE_DIM, LOG_Q, HW, HYBRID, LWE_HYBRID]
HEADERS_LAMBDA_HYBRID_NO_VERIFY = [SECRET_DIST, LWE_DIM, LOG_Q, HW, HYBRID]

HEADERS_LAMBDA_VERIFY = [SECRET_DIST, LWE_DIM, LOG_Q, OUTPUT, LWE]
HEADERS_LAMBDA_NOTABLE = [SECRET_DIST, LWE_DIM, LOG_Q, OUTPUT]

HEADERS_STD_E_VERIFY = [SECRET_DIST, LAMBDA, LWE_DIM, LOG_Q, OUTPUT, LWE_USVP, LWE_BDD]
HEADERS_STD_E_NOTABLE = [SECRET_DIST, LAMBDA, LWE_DIM, LOG_Q, OUTPUT]

HEADERS_N_VERIFY = [SECRET_DIST, LAMBDA, LOG_Q, OUTPUT, POW, USVP_NUM, BDD_NUM]
HEADERS_N_NOTABLE = [SECRET_DIST, LAMBDA, LOG_Q, OUTPUT, POW]

HEADERS_LOGQ_VERIFY = [SECRET_DIST, LAMBDA, LWE_DIM, OUTPUT, LWE_USVP, LWE_BDD]
HEADERS_LOGQ_NOTABLE = [SECRET_DIST, LAMBDA, LWE_DIM, OUTPUT]